<?php
/**
 * @file
 * Main hooks for Islandora Altmentrics.
 */

/**
 * Implements hook_block_info().
 */
function islandora_altmetrics_block_info() {
  return array(
    'islandora_altmetrics_altmetrics' => array(
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => 'islandora/object/*',
      'cache' => DRUPAL_NO_CACHE,
      'info' => t('Islandora Altmetrics'),
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function islandora_altmetrics_block_view($delta) {
  $to_render = array();

  switch ($delta) {
    case 'islandora_altmetrics_altmetrics':
      $object = menu_get_object('islandora_object', 2);
      // Limit to citations.
      if (!in_array('ir:citationCModel', $object->models)) {
        return;
      }
      // @todo: Get DOI.
      $doi = '10.1016/j.jsams.2014.03.003';
      if (!$doi) {
        return;
      }
      $to_render['subject'] = t('Altmetrics');
      // Embed Altmetrics.
      $to_render['content']['altmetrics'] = array(
        '#type' => 'container',
        '#attributes' => array(
          'class' => array('altmetric-embed'),
          'data-badge-type' => 'donut',
          'data-doi' => $doi,
        ),
        '#markup' => '@todo: content',
      );
      drupal_add_js('https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js', 'external');
      break;
  }
  return $to_render;
}
